apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:2.7.0
        ports:
        - containerPort: 9092
          name: internal
          protocol: TCP
        - containerPort: 9093
          name: external
          protocol: TCP
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: ":2181"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_CFG_LISTENERS
          value: "CLIENT://:9092,EXTERNAL://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "CLIENT://:9092,EXTERNAL://kafka-svc:9093"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "CLIENT"
      - name: zookeeper
        image: bitnami/zookeeper:3.6.2
        ports:
        - containerPort: 2181
          name: internal
          protocol: TCP
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
