apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
spec:
  selector: kafka
  ports:
    - name: internal
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: external
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: kafka
